
project_id = "thsjfdmivfxdmymcpnxf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[[functions]]
name = "extract-url-content"

[[functions]]
name = "generate-combined-keywords"

[[functions]]
name = "generate-keywords"

[[functions]]
name = "generate-secondary-keywords"

[[functions]]
name = "handle-workspace-creation"

[[functions]]
name = "track-api-usage"

[[functions]]
name = "analyze-seo-content"

[[functions]]
name = "analyze-competitors"
